### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by benedictHUN** [yuk1c/antiddos#7]
The script works great, but it does not work with the docker at all. I run the script and only the services that are not in the docker container remain available. Docker adds the NAT rules automatically but it doesn't work. 

Maybe I'm an amateur, but I'd like to ask for help on what this could be. Has anyone else experienced something similar?

**Comment by yuk1c** [comment]
Hey!
Can you show me iptables -L and nft list ruleset before the script runs? Maybe docker adds rules that are being deleted by this script, and that's why network didn't work anymore after this.

And after you restart docker - are you still experiencing this problem? Or network works OK?

**Comment by benedictHUN** [comment]
I've tried restarting the docker because it regenerates the rules but that didn't solve the problem either. All services that work outside the docker. 

[nft-rules.txt](https://github.com/yuk1c/antiddos/files/10745053/nft-rules.txt)
[iptables-rules.txt](https://github.com/yuk1c/antiddos/files/10745055/iptables-rules.txt)

**Comment by benedictHUN** [comment]
Web server is not in a docker container and is available but the mail server is not because it is in a docker container.

**Comment by yuk1c** [comment]
Seems like that script resets all needed rules and it causes problems.
After restarting u get zero changes?

And also when you have sysctl.conf tweaks - you also get this problem? Or they didn't causes problems?

Your answer will help me determine why this problem happens.

**Comment by benedictHUN** [comment]
**Problem successfully solved!** 
After running the script, the docker rules were not deleted, but blocking the 172.16.0.0/12 ip range caused a big problem because by default the docker network uses the 172.17.0.0/16 ip range.
