### ISSUE TITLE
how can i delete it

### ISSUE THREAD

**Issue by manouel-1** [yuk1c/antiddos#8]
I want to delete its causing problems

**Comment by yuk1c** [comment]
you see problems after an update or what?
if u wanna fully remove the script:
sudo nft flush ruleset && sudo ipset destroy blacklist, it will remove all nftables rules and delete "blacklist" ipset set.

to remove sysctl.conf you can restore the previous sysctl.conf file from sysctl.conf.backup file (smth similar to it)

that's all.
(and, ofc, remove antiddos folder)
