### ISSUE TITLE
which firewall should I use with your script?

### ISSUE THREAD

**Issue by goosegit11** [yuk1c/antiddos#9]
написано, что будут траблы с ufw 
какой тогда использовать? firewalld?

**Comment by vilander1337** [comment]
брат, юки в дурке, ответа не будет

**Comment by yuk1c** [comment]
все, что добавляет разрешающие правила в iptables и ставит drop policy будет вызывать проблемы после скрипта т.к. он сносит все рулы не меняя policy на accept

позже сделаю смену политики input & output на allow, если не перейду на drop..

а вообще, не советую юзать что-то похожее на скрипт вместе с ним, он должен один стоять

**Comment by yuk1c** [comment]
ставишь скрипт, затем добавляешь нужные рулы и забываешь про апдейты либо делаешь первые два действия каждый раз после выхода нового апдейта
либо делаешь форк и добавляешь те самые специфичные рулы в скрипт
на данный момент это единственные фиксы
